import CryptoKit
import Foundation

public struct LinkKeys: Sendable {
    public let tlsKey: SymmetricKey
    public let proofKey: SymmetricKey

    init(inputKeyMaterial: Data, purpose: String) {
        tlsKey = Self.derive(inputKeyMaterial, label: "\(purpose) tls psk")
        proofKey = Self.derive(inputKeyMaterial, label: "\(purpose) proof")
    }

    private static func derive(_ material: Data, label: String) -> SymmetricKey {
        HKDF<SHA256>.deriveKey(
            inputKeyMaterial: SymmetricKey(data: material),
            salt: Data("co.sharepad.wire.v1".utf8),
            info: Data(label.utf8),
            outputByteCount: 32
        )
    }
}

// The one-time code behind both the QR and the typed fallback. 120 bits is far past
// what an attacker could guess offline inside the 5-minute window (specs §6, Q9).
public struct PairingCode: Equatable, Sendable {
    public static let byteCount = 15
    public static let alphabet = Array("0123456789ABCDEFGHJKMNPQRSTVWXYZ")
    static let characterCount = 24
    static let groupLength = 4
    static let invitationHost = "sharepad.co"
    static let invitationPath = "/pair"
    static let invitationPrefix = "v1."

    public let bytes: Data

    public init?(bytes: Data) {
        guard bytes.count == Self.byteCount else { return nil }
        self.bytes = Data(bytes)
    }

    private init(generated bytes: Data) {
        self.bytes = bytes
    }

    public static func generate() -> PairingCode {
        var generator = SystemRandomNumberGenerator()
        return generate(using: &generator)
    }

    public static func generate(using generator: inout some RandomNumberGenerator) -> PairingCode {
        let bytes = Data((0 ..< byteCount).map { _ in UInt8.random(
            in: .min ... .max,
            using: &generator
        ) })
        return PairingCode(generated: bytes)
    }

    public var typed: String {
        let characters = compact
        return stride(from: 0, to: characters.count, by: Self.groupLength).map { start in
            let begin = characters.index(characters.startIndex, offsetBy: start)
            let end = characters.index(begin, offsetBy: Self.groupLength)
            return String(characters[begin ..< end])
        }.joined(separator: "-")
    }

    public init?(typed text: String) {
        var values: [UInt8] = []
        for character in text.uppercased() {
            if " -·.\t".contains(character) { continue }
            guard let value = Self.value(of: character) else { return nil }
            values.append(value)
        }
        guard values.count == Self.characterCount else { return nil }
        self.init(bytes: Self.unpack(values))
    }

    public var invitationURL: URL? {
        var components = URLComponents()
        components.scheme = "https"
        components.host = Self.invitationHost
        components.path = Self.invitationPath
        components.fragment = Self.invitationPrefix + compact
        return components.url
    }

    public init?(invitation url: URL) {
        guard
            let components = URLComponents(url: url, resolvingAgainstBaseURL: false),
            components.scheme?.lowercased() == "https",
            components.host?.lowercased() == Self.invitationHost,
            components.path == Self.invitationPath,
            components.query == nil,
            let fragment = components.fragment,
            fragment.hasPrefix(Self.invitationPrefix)
        else { return nil }
        let code = fragment.dropFirst(Self.invitationPrefix.count)
        guard code.count == Self.characterCount, code.allSatisfy(Self.alphabet.contains) else {
            return nil
        }
        self.init(typed: String(code))
    }

    public var keys: LinkKeys {
        LinkKeys(inputKeyMaterial: bytes, purpose: "pairing")
    }

    private var compact: String {
        var characters = ""
        var buffer = 0
        var bits = 0
        for byte in bytes {
            buffer = (buffer << 8) | Int(byte)
            bits += 8
            while bits >= 5 {
                bits -= 5
                characters.append(Self.alphabet[(buffer >> bits) & 31])
            }
        }
        return characters
    }

    private static func value(of character: Character) -> UInt8? {
        switch character {
        case "O": 0
        case "I", "L": 1
        default: alphabet.firstIndex(of: character).map(UInt8.init)
        }
    }

    private static func unpack(_ values: [UInt8]) -> Data {
        var bytes = Data()
        var buffer = 0
        var bits = 0
        for value in values {
            buffer = (buffer << 5) | Int(value)
            bits += 5
            if bits >= 8 {
                bits -= 8
                bytes.append(UInt8(truncatingIfNeeded: buffer >> bits))
            }
        }
        return bytes
    }
}

extension PairingCode: CustomStringConvertible, CustomDebugStringConvertible {
    public var description: String {
        "PairingCode(redacted)"
    }

    public var debugDescription: String {
        description
    }
}

public struct LinkSecret: Equatable, Sendable {
    public static let byteCount = 32

    public let bytes: Data

    public init?(bytes: Data) {
        guard bytes.count == Self.byteCount else { return nil }
        self.bytes = Data(bytes)
    }

    private init(generated bytes: Data) {
        self.bytes = bytes
    }

    public static func generate() -> LinkSecret {
        var generator = SystemRandomNumberGenerator()
        let bytes = Data((0 ..< byteCount).map { _ in UInt8.random(
            in: .min ... .max,
            using: &generator
        ) })
        return LinkSecret(generated: bytes)
    }

    public var keys: LinkKeys {
        LinkKeys(inputKeyMaterial: bytes, purpose: "link")
    }
}

extension LinkSecret: CustomStringConvertible, CustomDebugStringConvertible {
    public var description: String {
        "LinkSecret(redacted)"
    }

    public var debugDescription: String {
        description
    }
}
